server:
  port: 80
spring:
  application:
    name: springcloud-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
      prefer-ip-address: true  #eureka显示ip地址
      lease-renewal-interval-in-seconds: 5  #每隔5秒发送一次心跳
      lease-expiration-duration-in-seconds: 10 #每隔10秒不发生就过期
feign:
  hystrix:
    enabled: true

